### ISSUE TITLE
Line 539:SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by nguyencaothiem** [hardeepnarang10/attendance-automation#1]
Dear Friends!

Thanks for sharing and public your project. It's the best!
Could you explain and fix help me the error:
File "application.py", line 539: msg['Subject'] = f'Lecture Attendance: {lecture}'

**Comment by hardeepnarang10** [comment]
`msg['Subject'] = f'Lecture Attendance: {lecture}'` - sets the name of the lecture/course as the subject of the email.
Sorry for the late reply. Can you post the complete error log?
